---
language: ruby
rvm:
  - 1.9.3
  - 1.9.2
before_script:
- git clone git@github.com:cotap/chef-repo.git ../chef-repo
- bundle exec berks install --path vendor/cookbooks --except development

script:
- bundle exec rake foodcritic spec rubocop
